FROM codewars/node-runner
 
USER root

VOLUME ./server:/var/www/code
WORKDIR /var/www/code
## docker build -f DockerFile -tag chynorun .
##RUN npm install -g pm2

##RUN mkdir -p /var/log/pm2

EXPOSE 		9002
#CMD node index.js
#ENTRYPOINT ["node",  "index.js"]
##ENTRYPOINT ["pm2",  "index.js", "--log","/var/log/pm2/pm2.log","--watch","--no-daemon"]


# To build:
# docker build -f docker-node-codewithdan.dockerfile --tag codewithdan_node ../

# To run:
# docker run -d -p 8080:8080 -v $(PWD):/var/www/codewithdan -w /var/www/codewithdan codewithdan_node
# docker run -d -p 8080:8080 --name codewithdan_node codewithdan_node 
