version: '2'
services:
  javascript:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "9001:3000"
    image: codewars/node-runner
    volumes:
      - ./server:/runner/chynotest/src
    user: root
    entrypoint: 'node run /runner/chynotest/index.js'
    


    ##entrypoint: 'node run -l javascript' 
    