version: '2'
services:
  node-runner:
    image: chynorunner
    volumes:
      - c:/dev/chynotestapp/server:/runner/www
    ports : 
      - "9002:9002"
    entrypoint: bash
    stdin_open: true
    tty: true
   #docker run -it -p 9002:9002  --rm --entrypoint  bash -v c:/dev/chynotestapp/server:/var/www chynorun
#ENTRYPOINT ["npm", "start", "index.js"]
 #   - ./lib:/runner/lib
   #   - ./examples:/runner/examples
   #   - ./frameworks:/runner/frameworks
   #   - ./test:/runner/test