version: '3'
services:
    node-runner:
    image: codewars/node-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
      - ./tsconfig.json:/runner/tsconfig.json

    entrypoint: ''
    user: root
    command: bash
    
    #entrypoint : ["npm", "start", "index.js"]

   #docker run -it -p 9002:9002  --rm --entrypoint  bash -v c:/dev/chynotestapp/server:/runner/wwwAq chynorun
#ENTRYPOINT ["npm", "start", "index.js"]
 #   - ./lib:/runner/lib
   #   - ./examples:/runner/examples
   #   - ./frameworks:/runner/frameworks
   #   - ./test:/runner/test

    #entrypoint: bash
   # stdin_open: true
   # tty: true