version: '2'
services:
 
  node-runner:
    image: codewars/node-runner
    volumes:
      - ./lib:/runner/lib
 
    entrypoint: ''
    user: root
    command: bash 
    ##command: /bin/echo 'Hello world from chyno test'
